name: Deploy New Version
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_name:
        required: true
        type: string
      cloud_run_service_name:
        required: true
        type: string
      project_id:
        required: true
        type: string
      gcp_region:
        required: true
        type: string
      gcp_tf_bucket_name:
        required: true
        type: string
      gcp_registry_name:
        required: true
        type: string
      gcp_zone:
        required: false
        type: string
      gcp_registry_hostname:
        required: false
        type: string
      extra_env_vars:
        required: false
        type: string
    secrets:
        GCP_SERVICE_ACCOUNT_FILE:
            required: true
        GITUB_ACCESS_TOKEN:
          required: false
        GITUB_SSH_KEY:
          required: false
        extra_secrets:
          required: false
jobs:
  deploy_new_version:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "VARIABLES_CONFIG_PATH=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "GCP_PROJECT_ID=${{ inputs.project_id }}" >> $GITHUB_ENV
          echo "GCP_REGION=${{ inputs.gcp_region }}" >> $GITHUB_ENV
          echo "GCP_ZONE=${{ inputs.gcp_zone }}" >> $GITHUB_ENV
          echo "GCP_TF_BUCKET_NAME=${{ inputs.gcp_tf_bucket_name }}" >> $GITHUB_ENV
          echo "GCP_CONTAINER_REGISTRY_NAME=${{ inputs.gcp_registry_name }}" >> $GITHUB_ENV
          echo "GCP_CONTAINER_REGISTRY_HOSTNAME=${{ inputs.gcp_registry_hostname }}" >> $GITHUB_ENV

      - name: Set extra environment variables
        if: ${{ inputs.extra_env_vars != '' }}
        run: |
          echo "${{ inputs.extra_env_vars }}" | tr ',' '\n' | while read -r var; do
            echo "$var" >> $GITHUB_ENV
          done

      - name: Set extra secrets
        if: ${{ secrets.extra_secrets != '' }}
        run: |
          echo "${{ secrets.extra_secrets }}" | tr ',' '\n' | while read -r secret; do
            echo "$secret" >> $GITHUB_ENV
          done

      - name: Set derived image full name
        run: echo "FULL_IMAGE_NAME=${{ inputs.gcp_region }}-docker.pkg.dev/${{ inputs.project_id }}/${{ inputs.gcp_registry_name }}/${{ inputs.image_name }}" >> $GITHUB_ENV

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_FILE }}
          project_id: ${{ inputs.project_id }}
          token_format: access_token

      - name: Deploy new Cloud Run Image
        id: deploy_new_cloud_run_image
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          project_id: ${{ inputs.project_id }}
          service: ${{ inputs.cloud_run_service_name }}
          image: "${{ env.FULL_IMAGE_NAME }}:latest"
          region: ${{ inputs.gcp_region }}
          env_vars: |-
            ENVIRONMENT=${{ inputs.environment }}
            VARIABLES_CONFIG_PATH=${{ inputs.environment }}
            
      - name: Use output
        run: curl "${{ steps.deploy_new_cloud_run_image.outputs.url }}"
